env:
  es6: true
  mocha: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - import
  - mocha
  - prettier
rules:
  prettier/prettier: error
  mocha/no-exclusive-tests: error
  consistent-return: off
  import/prefer-default-export: off
overrides:
  files:
    - '*.test.js'
  rules:
    no-unused-expressions: 'off'
